### ISSUE TITLE
【新应用推荐】atvloadly  一个支持在 AppleTV 上侧载应用的 web 服务

### ISSUE THREAD

**Issue by cyril-cheng** [okxlin/appstore#2703]
项目介绍：https://github.com/bitxeno/atvloadly/blob/master/README_cn.md
docker排版：https://github.com/bitxeno/atvloadly/blob/master/docker-compose.yml

**Comment by cyril-cheng** [comment]
安装应用报错了
1Panel-atvloadly-D3o9  | Load config from path: /data/config.yaml
1Panel-atvloadly-D3o9  | [WARN] Config file not exists. path: /data/settings.json
1Panel-atvloadly-D3o9  | Log file path: /data/app.log
1Panel-atvloadly-D3o9  | Load database from path: /data/app.db
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [INFO]     source/internal/log/log.go:132> Log file: /data/app.log
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [INFO]     source/internal/log/log.go:82> App refresh scheduled task has started, time: 0,30 3-6 * * *
1Panel-atvloadly-D3o9  | Starting server version: v0.2.5@2024-10-25-09:04:29@production
1Panel-atvloadly-D3o9  | 
1Panel-atvloadly-D3o9  |  ┌───────────────────────────────────────────────────┐ 
1Panel-atvloadly-D3o9  |  │                   Fiber v2.52.5                   │ 
1Panel-atvloadly-D3o9  |  │                http://127.0.0.1:80                │ 
1Panel-atvloadly-D3o9  |  │        (bound on host 0.0.0.0 and port 80)        │ 
1Panel-atvloadly-D3o9  |  │                                                   │ 
1Panel-atvloadly-D3o9  |  │ Handlers ............ 45  Processes ........... 1 │ 
1Panel-atvloadly-D3o9  |  │ Prefork ....... Disabled  PID ................ 14 │ 
1Panel-atvloadly-D3o9  |  └───────────────────────────────────────────────────┘ 
1Panel-atvloadly-D3o9  | 
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:39> GetHostName() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:45> GetHostNameFqdn() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:51> GetAlternativeHostName() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:57> GetAPIVersion() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:63> ResolveHostName() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:69> ServiceBrowserNew() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [ERROR]    source/internal/manager/device_manager_avahi.go:74> ServiceBrowserNew() failed: The name org.freedesktop.Avahi was not provided by any .service files
1Panel-atvloadly-D3o9  | 2025-01-19 09:07:44      [INFO]     source/internal/log/log.go:78> mDNS discovery started...
1Panel-atvloadly-D3o9  | panic: runtime error: invalid memory address or nil pointer dereference
1Panel-atvloadly-D3o9  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc558e9]
1Panel-atvloadly-D3o9  | 
1Panel-atvloadly-D3o9  | goroutine 11 [running]:
1Panel-atvloadly-D3o9  | github.com/bitxeno/atvloadly/internal/manager.(*DeviceManager).Start(0x1708040)
1Panel-atvloadly-D3o9  | 	/source/internal/manager/device_manager_avahi.go:83 +0x589
1Panel-atvloadly-D3o9  | created by github.com/bitxeno/atvloadly/internal/manager.StartDeviceManager in goroutine 1
1Panel-atvloadly-D3o9  | 	/source/internal/manager/manager.go:6 +0x58
